services:
  mysql:
    image: mysql:8.0
    container_name: classetrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: classetrack
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - classetrack-network

volumes:
  mysql-data:

networks:
  classetrack-network:
    driver: bridge
